name: JavaDoc erzeugen und veröffentlichen

on:
  push:
    branches: [ "master" ]

jobs:
  baue-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: JavaDoc erzeugen und mit GHPages bereitstellen
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0 # Doku: https://github.com/marketplace/actions/deploy-publish-javadoc
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc-zweig 
          java-version: 21
          target-folder: # url will be https://<username>.github.io/<repo>/javadoc, This can be left as nothing to generate javadocs in the root folder.
          project: maven # or gradle    
